use_frameworks!

target 'Themeful_Example' do
  pod 'Themeful', :path => '../'

  pod 'SwiftyJSON'
  target 'Themeful_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
  end
end
